### ISSUE TITLE
Instructions on where to find an embed id

### ISSUE THREAD

**Issue by AndrewBarba** [Driftt/drift-sdk-ios#21]
Can you provide real instructions on where to find the embed id? Currently it links to settings page in web app which isn't helpful

**Comment by eoinoconnell** [comment]
Hi, sorry that actually changed recently, we are working on adding it back to settings but for now your best bet is to talk to support

**Comment by alaamonther** [comment]
go to settings > live chat > install > javascript, look for a text that says `drift.load('<app id here>')`

this answer from their support team.
