### ISSUE TITLE
Build Issue With Drift

### ISSUE THREAD

**Issue by Abhishek-weboniselab** [Driftt/drift-sdk-ios#25]
Hello Team,
I have installed your library using pods and compiling the code in Xcode 8.2.1, but it gives me below error:
The following binaries use incompatible versions of Swift:
/Users/webonise/Library/Developer/Xcode/DerivedData/MyAppName-boitjuuxzbvjagccgybzbdwcptue/Build/Products/Debug-iphonesimulator/MyAppName.app/MyAppName
/Users/webonise/Library/Developer/Xcode/DerivedData/MyAppName-boitjuuxzbvjagccgybzbdwcptue/Build/Products/Debug-iphonesimulator/MyAppName.app/Frameworks/Alamofire.framework/Alamofire

MyAppName is the name of my app.

Waiting for your reply.
Thanks.

**Comment by eoinoconnell** [comment]
Hey @Abhishek-weboniselab, What version of swift are you using? The library is built on swift 3. 

It may be worth updating to 8.3 also,

Thanks

**Comment by Abhishek-weboniselab** [comment]
Thanks for replying.
I was running chart library with swift 2.3 code which caused error.

**Comment by eoinoconnell** [comment]
No problem!
