### ISSUE TITLE
Conversation VC on client side not updating

### ISSUE THREAD

**Issue by timcorpa** [Driftt/drift-sdk-ios#27]
When you have a conversation with the client and you send a new message the client has to go back to list view or change view to update. Being a live chat you shouldn't have to?

**Comment by brianmcdon** [comment]
@timcorpa you certainly shouldn't have to, live chat messages should be shown as long as the client has an internet connection which is indicated by the slim bar on top of the Conversation view (Green for connected, red for disconnected). Has the client received any messages without having to change back to the list view?

**Comment by timcorpa** [comment]
@brianmcdon that's the thing. When you start a chat. On the client side they don't receive the messages unless they switch view. Appreciate the help! Thanks!

**Comment by brianmcdon** [comment]
@timcorpa ok thanks. Can you confirm you see the slim green bar as in the attached image when the issue occurs? 
![drift](https://user-images.githubusercontent.com/1974207/29267695-ab038b2a-80e1-11e7-98ea-fcca93855844.jpg)

**Comment by timcorpa** [comment]
@brianmcdon client side no I don't see that green bar. Only on our side. What am I missing?

![img_3017](https://user-images.githubusercontent.com/13125414/29288434-958d8ec4-80ed-11e7-8748-61806f29ecde.PNG)

**Comment by brianmcdon** [comment]
@timcorpa thanks for the screenshot, which version (version number) of the SDK are you using? Also have you had the same issue on a non iOS 11 device?

**Comment by timcorpa** [comment]
@brianmcdon Thanks! we are using  'Drift', '~> 1.0.1' SDK version. We have only tried iOS as thats where our focus is right now.

**Comment by brianmcdon** [comment]
@timcorpa can you try 1.1.0 and see if that resolves the issue. I see our readme is out of date and still recommends 1.0.1

**Comment by timcorpa** [comment]
@brianmcdon Worked thank you! It was the version issue after all.
