### ISSUE TITLE
 linker command failed with exit code 1 (use -v to see invocation

### ISSUE THREAD

**Issue by pravishanth** [Driftt/drift-sdk-ios#31]
Downloaded your drift-idk-ios folder, ran pod install.
 when I build it in Xcode I get the error " linker command failed with exit code 1 (use -v to see invocation"

**Comment by eoinoconnell** [comment]
Hi, What directory did you run pod install on. Are you trying to run the example application?

**Comment by pravishanth** [comment]
Wow thats quick response!!

Yeah, I am trying to run example application, ran pod install on master folder which has the pod file. And then opened .xcworkspace, I get the the error when I run the application in Xcode, " linker command failed with exit code 1 (use -v to see invocation"

**Comment by eoinoconnell** [comment]
Heh yeah! 

So you want to navigate to Example/SDKExample/ and run pod install on that pod file and then you should be able to run SDKExample.xcworkspace

Ill check on my end too, what Xcode are you using?

**Comment by pravishanth** [comment]
Xcode 8.3.3

**Comment by eoinoconnell** [comment]
Ok cool, thats working for me against Xcode 9. Did that work for you in the new directory?

**Comment by pravishanth** [comment]
The example app loaded successfully, it shows a loading icon, I guess I need to create an account.  Will follow the readme instructions and try it.

**Comment by eoinoconnell** [comment]
Yeah you will need to get your embed id from settings to use the SDK I'm afraid

**Comment by eoinoconnell** [comment]
You should be all set for now, I'll close this for now and let us know if you have any other issues
