### ISSUE TITLE
Update ObjectMapper to version 3.0 so it's compatible with Swift 4 projects

### ISSUE THREAD

**Issue by AndrewBarba** [Driftt/drift-sdk-ios#32]
Currently if we are building an app in Swift 4, ObjectMapper will fail to build. Can you update to the latest version of ObjectMapper?

**Comment by eoinoconnell** [comment]
Hey, ill take a look tomorrow and get back to you asap

**Comment by eoinoconnell** [comment]
Hey, version 1.2.0 went live there and should work for you. Let me know if you have any other issues.

**Comment by AndrewBarba** [comment]
Amazing thank you!
