### ISSUE TITLE
Adding messages to an existing chat crashes the app

### ISSUE THREAD

**Issue by audungk** [Driftt/drift-sdk-ios#34]
If you try to write and submit a new message to an existing chat, it crashes Drift. This happens in both simulator and device(iPhone 7+, iOS11.01)

**Comment by brianmcdon** [comment]
Hi Audun, are you seeing this behaviour in the example app or in your own app with the Drift SDK installed?
Also it would be great if you could provide a stacktrace to help us track down the issue.

**Comment by audungk** [comment]
The example app doesn't build in XCode9 yet, so this is from our integration. I'll try to get a Stacktrace!

**Comment by audungk** [comment]
```2017-10-04 14:01:39.017115+0200 Spiff[2383:963646] *** Assertion failure in -[UITableView _endCellAnimationsWithContext:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3694.4.18/UITableView.m:1950
2017-10-04 14:01:39.020214+0200 Spiff[2383:963646] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (4) must be equal to the number of rows contained in that section before the update (3), plus or minus the number of rows inserted or deleted from that section (1 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).'
*** First throw call stack:
(0x182fdfd38 0x1824f4528 0x182fdfc0c 0x18396ec24 0x18c5b668c 0x18c711f20 0x18c5f2f70 0x105d99200 0x105dede04 0x105daca48 0x105bdb998 0x105b9c46c 0x10804549c 0x10804545c 0x10804a050 0x182f87f20 0x182f85afc 0x182ea62d8 0x184d37f84 0x18c453880 0x105096044 0x1829ca56c)
libc++abi.dylib: terminating with uncaught exception of type NSException```

**Comment by audungk** [comment]
<img width="327" alt="screen shot 2017-10-04 at 14 03 58" src="https://user-images.githubusercontent.com/150725/31174768-f94e40e2-a90c-11e7-9fd6-49a0f6f66283.png">

**Comment by audungk** [comment]
```
[Birdsong]: Connected to: <Starscream.WebSocket: 0x111d16e60>
[Birdsong]: Sending: [:]
[Birdsong]: Received message: ["status": ok, "response": {
}]
2017-10-04 14:13:57.985078+0200 Spiff[2418:969939] [MC] Lazy loading NSBundle MobileCoreServices.framework
2017-10-04 14:13:57.988637+0200 Spiff[2418:969939] [MC] Loaded MobileCoreServices.framework
Successfully marked conversation as read
Unable to post message for conversationId: 35482408
```

FWIW, it seems like it shouldn't be possible to add messages here?

**Comment by brianmcdon** [comment]
Great thanks for the info to help with debugging.
The Example should run in Xcode 9. You will need to ensure that the Drift target is being built with `Swift Language Version` -> `Swift 4.0`
![screen shot 2017-10-04 at 14 05 51](https://user-images.githubusercontent.com/1974207/31177281-73876762-a90d-11e7-868a-2892f20bc313.png)

**Comment by audungk** [comment]
It crashes in the example-app as well. Could it be because we are on a free account for Drift?

**Comment by eoinoconnell** [comment]
Hey @audungk, I was able to reproduce the crash for when posting the message fails so I will get a release together to resolve that. I will continue to look into why your account is failing to post and get back to you

**Comment by eoinoconnell** [comment]
Hey @audungk, mind if I send a few messages to your org to try reproduce the issue?

**Comment by audungk** [comment]
Please do! Let me know if there is anything we can do to help!

**Comment by eoinoconnell** [comment]
Hi @audungk sorry for the delay, I just checked out the app there and it seems to work with me for your org. Can you try 1.2.1 and see if it works for you?

**Comment by eoinoconnell** [comment]
Hi @audungk sorry about the wait, I was able to reproduce your issue and pushed 1.2.2 to resolve the issue for you. Let me know if you have any other issues.

**Comment by audungk** [comment]
No other issues so far, thanks for all your help!
