### ISSUE TITLE
ConversationViewController fails building in v. 1.2.2

### ISSUE THREAD

**Issue by audungk** [Driftt/drift-sdk-ios#37]
When building with Drift as a Pod under the latest Xcode, v.1.2.2 complains: 
_A non-failable initializer cannot delegate to failable initializer 'init(tableViewStyle:)' written with 'init?'_

For reference, lines 72-75
```
convenience init(conversationType: ConversationType) {
        self.init(tableViewStyle: UITableViewStyle.grouped)
        setConversationType(conversationType)
}
```

**Comment by eoinoconnell** [comment]
Hi there, sorry about the delay, v1.2.3 should be available now to resolve this for you
