### ISSUE TITLE
All Archive campaign are visible for most of the User.

### ISSUE THREAD

**Issue by shastrikikitchen** [Driftt/drift-sdk-ios#49]
Hi, even after the fix in 2.0 which says "Removed deprecated NPS Campaigns" There is another thing which is showing all the archived campaigns  which are getting displayed to users. Can you please look into the issue , our release is blocked due to your unwanted issue. Hope you guys fix it as soon as possible.

**Comment by eoinoconnell** [comment]
Hi there, just talked to the automation team here. So if a campaign / playbook is delivered to a user it will not disappear once a campaign is archived so as it doesn't disappear from the users conversation lists etc. Once the user dismisses or responds to the campaign it should no longer appear. One thing to note is for testing purposes if the SDK is in debug mode the campaign will not be marked as read and will continue to show. Could this be the case for you?

**Comment by shastrikikitchen** [comment]
Issue is strange, app is not in debug mode, very old campaigns are coming to old users, we can share the screen shots 
![img_0197](https://user-images.githubusercontent.com/21083457/38149921-39b8334c-347a-11e8-81ca-f36e8191fd24.PNG)
![img_0229](https://user-images.githubusercontent.com/21083457/38149922-39f5d792-347a-11e8-9174-fadfb5d34096.PNG)
![img_0230](https://user-images.githubusercontent.com/21083457/38149923-3a31295a-347a-11e8-83f4-cb1af1be9c13.PNG)
![img_0231](https://user-images.githubusercontent.com/21083457/38149924-3a989072-347a-11e8-9d5d-1e4b50c06f89.PNG)
![img_0233](https://user-images.githubusercontent.com/21083457/38149925-3ad5d14e-347a-11e8-95e7-d7e1d1153eef.PNG)
![img_0234](https://user-images.githubusercontent.com/21083457/38149926-3b117e10-347a-11e8-8219-37304d56a79c.PNG)
![img_0235](https://user-images.githubusercontent.com/21083457/38149928-3b5496a0-347a-11e8-9916-706bff65531e.PNG)
![img_0236](https://user-images.githubusercontent.com/21083457/38149929-3b9aeeac-347a-11e8-8cd2-8192fa008230.PNG)
![img_0237](https://user-images.githubusercontent.com/21083457/38149930-3bd6ea60-347a-11e8-8d5c-820efd751d73.PNG)
![img_0238](https://user-images.githubusercontent.com/21083457/38149932-3c11fcd6-347a-11e8-94b2-119a51a848cd.PNG)
![img_0239](https://user-images.githubusercontent.com/21083457/38149933-3c5d9c18-347a-11e8-91f1-a2045dc5cc37.PNG)
![img_0240](https://user-images.githubusercontent.com/21083457/38149934-3ca1215e-347a-11e8-97d9-6c2c3be75434.PNG)
![img_0241](https://user-images.githubusercontent.com/21083457/38149935-3ce22852-347a-11e8-9142-2bd2790b0e9e.PNG)
![img_0242](https://user-images.githubusercontent.com/21083457/38149936-3d4bf944-347a-11e8-9b9f-b3e634894ff8.PNG)

**Comment by eoinoconnell** [comment]
Thats great thanks, I think we have a solution, I got some more context from Julie and should have something for you soon

**Comment by shastrikikitchen** [comment]
Thanks, waiting for an update soon.

**Comment by eoinoconnell** [comment]
Hello, we believe we have a fix for this issue but are still running tests, could you try this version and let us know if the issue persists: 

```
pod 'Drift', :git => 'git@github.com:8bytes/drift-sdk-ios', :branch => 'release2.1'
```

This is not meant for release, that will follow once we complete testing

**Comment by eoinoconnell** [comment]
You will also need to use 
```
        Drift.showArchivedCampaignsForEndUser(false)
```

During setup

**Comment by shastrikikitchen** [comment]
We are not able to integrate the above branch

**Comment by eoinoconnell** [comment]
Could you elaborate? Are you getting an error through cocoa pods or Xcode?

**Comment by shastrikikitchen** [comment]
we are getting error through cocoa pods
Pre-downloading: `Drift` from `git@github.com:8bytes/drift-sdk-ios`, branch `release2.1`
[!] Error installing Drift
[!] Failed to download 'Drift'.

**Comment by eoinoconnell** [comment]
Hey, that seems strange, we just pushed release 2.1 that should fix the issue for you so you can use that: `pod 'Drift', '~> 2.1'`
