### ISSUE TITLE
Add private keywords to functions and remove references to IBDesignable in SDK

### ISSUE THREAD

**Issue by audungk** [Driftt/drift-sdk-ios#51]
When integrating Driftt via Cocoapods, there are some issues that are mildly frustrating at the current version. Due to the lack of `private` declarations in the code base, some of the functions declared in drift bleed into the codebase embedding Drift. This should mostly be no problem, but there are some extensions in Drift named similarly to extensions that can be imagined used in a hosting code base, where functionality is slightly different. If these are functions required to display drift UI, they should be marked as private, and a user embedding the SDK should be forced to implement their own. 

Similarly views like `AvatarView` which is a generic name possible for hosting applications to be using gets into troubles due to `@IBInspectable` and `@IBDesignable` being declared on class level and thus gets picked up by Xcode. 

I guess a solution is to switch dependency management to Carthage, but it would be nice if the Drift SDK would prevent polluting public namespaces

**Comment by brianmcdon** [comment]
Thanks @audungk. We'll take a look and keep you updated.
