### ISSUE TITLE
Register User Error

### ISSUE THREAD

**Issue by PinkalBaleshwaria** [Driftt/drift-sdk-ios#56]
Hi, 
I want to show to user conversation in my application.
[Drift setup:@""]; is not working, it gives error in log 
"The operation couldn’t be completed. (Drift.DriftError error 0.)"

And While calling registerUser function is also gives error:
"No Embed, not registering user - Waiting for Embeds to complete"
Can you help me for this?

Thanks

**Comment by eoinoconnell** [comment]
Hey, yeah of course, I'll need a bit more information from you I'm afraid.

Could I get some code and your embed Id so I can reproduce it on my end? 

If you could send it in chat here: https://drift.me/trex so that its not public that would be great,

Thanks

**Comment by PinkalBaleshwaria** [comment]
Hi, it is resolved. There was an issue with cocoapod's version. So after updating to latest cocoapod version it's working now.

Thanks for quick response :)
