### ISSUE TITLE
Anonymous Chat Just like web

### ISSUE THREAD

**Issue by msalmanST** [Driftt/drift-sdk-ios#58]
Hi,

I want my app users to get help even without gets logged in to the app, so I don't want to ask for email address, is there a way to achieve this i.e start chat without providing email address.

Thanks

**Comment by eoinoconnell** [comment]
Hi, 

 I'm afraid this is currently not support in the SDK. As of now we don't have plans of adding that feature but I will take note of your request for when we plan out the next release

**Comment by msalmanST** [comment]
Thanks for your quick response, one more question, is there a way to pass some user information to the agent before we start the session so that agent wont ask any basic question

**Comment by eoinoconnell** [comment]
Hi sorry this slipped by me, I'm afraid that is also not currently support I'm afraid
