### ISSUE TITLE
Support Carthage

### ISSUE THREAD

**Issue by D-Mx** [Driftt/drift-sdk-ios#62]
Hello,

Can we get Carthage support?

**Comment by eoinoconnell** [comment]
Hi, let me see what I can do, I won't be able to get to it today but will take a look early next week

**Comment by D-Mx** [comment]
Thanks. I gave it a try but the cocoapods integration and dependencies in the framework were interfering with the carthage build. Ended up removing cocoapods in a fork for it to work.

**Comment by eoinoconnell** [comment]
Hi, I took a look at this this morning and you are correct. As the project is currently structured having Carthage and CocoaPods support seems pretty complex. Theres no quick fix for this I'm afraid. I will try get it into the next feature release but there is currently no timeline for that
