### ISSUE TITLE
Tapping on ConversationInputTextView pushes view up

### ISSUE THREAD

**Issue by D-Mx** [Driftt/drift-sdk-ios#63]
Hello,

We are getting a weird behavior where whenever we tap the input textfield the conversation content view gets pushed up but it only seems to happen three times then it stops moving.

<img width="461" alt="screen shot 2018-09-28 at 12 10 06 am" src="https://user-images.githubusercontent.com/409270/46189449-4c038100-c2b4-11e8-83a2-7d7c425af8b9.png">

<img width="1382" alt="screen shot 2018-09-28 at 12 12 40 am" src="https://user-images.githubusercontent.com/409270/46189538-a997cd80-c2b4-11e8-8039-85b2ca933c9f.png">

<img width="1349" alt="screen shot 2018-09-28 at 12 12 46 am" src="https://user-images.githubusercontent.com/409270/46189542-abfa2780-c2b4-11e8-826d-3f68d97d07aa.png">

**Comment by eoinoconnell** [comment]
Hi, thanks for that ill take a look. Does this happen on a physical device at all?

**Comment by D-Mx** [comment]
Oh I see, yeah on a physical device it is working properly. I guess the problem is that the keyboard is not appearing in the simulator so the view goes up to accommodate the keyboard showing but since it's not displaying it is also missing a hidding event when tapping outside so the view never goes down.

Well, it works. Thanks for answering.
