### ISSUE TITLE
Please update your read me to mention where we can get setup id

### ISSUE THREAD

**Issue by HabibAliAtFolio3** [Driftt/drift-sdk-ios#66]
Please update your read me to mention where we can get setup id

**Comment by brianmcdon** [comment]
Hi, your setup Id can be found by clicking the the link below and following the steps: 
https://app.drift.com/settings/livechat

- Choose "Install"
- Choose "JavaScript"
- Scroll to the bottom of the JavaScript code and you'll find you setup Id in this line: `drift.load('{your_setup_id}');`
