### ISSUE TITLE
Support localization

### ISSUE THREAD

**Issue by aalemayhu** [Driftt/drift-sdk-ios#85]
Hei,

the view loaded via `Drift.showCreateConversation()` has the strings in English. Do you have any way to use the same language as the Javascript widget?

Thanks.

**Comment by eoinoconnell** [comment]
Hi,

I'm afraid this is something we don't currently support with the SDK's, your best approach may be to fork the SDK to add your own localisations.

I will keep note of the request but I'm afraid it is not on our current roadmap

Thanks
