### ISSUE TITLE
Are real names a possibility?

### ISSUE THREAD

**Issue by FerrariBruno** [Driftt/drift-sdk-ios#87]
Hello, I've read the documentation and issues extensively and implemented the integration with Drift in my iOS app as instructed.

However, I noticed users that contact me through Drift on iOS don't have their real names (for example, I keep seeing "Brian Best" as a name). Is there currently any way to ask the user for his/her real name so we can avoid having fictional names?

Thank you!

**Comment by eoinoconnell** [comment]
Hi, sorry for the delay in getting back to you. The SDK itself does not create names for the end users, this would be done from the drift backend. Fictional names are not created, maybe its pulling them from a salesforce integration?

**Comment by FerrariBruno** [comment]
We do not have any integration with Salesforce or anything alike. I'm guessing Drift's backend is somehow creating fictional names?

**Comment by eoinoconnell** [comment]
Hi, Drift doesn't currently create fictional names, it may be recognising the email address of the end users somehow? I recon your best bet would be to reach out to drift support I'm afraid that should be able to give you more information. Sorry I can't be more help

**Comment by FerrariBruno** [comment]
No problem, thank you for your time
