### ISSUE TITLE
UI is broken when dark mode is enabled on iOS 13

### ISSUE THREAD

**Issue by seanhaufler** [Driftt/drift-sdk-ios#89]
When composing a message, the typed text is white on a white background. There are also other instances of dark mode making the UI look strange.

**Comment by eoinoconnell** [comment]
Hey, thanks for letting us know, ill try get this tomorrow and get an update together for you

**Comment by eoinoconnell** [comment]
Didn't get this rounded out today but will hopefully get it complete tomorrow

**Comment by eoinoconnell** [comment]
Hi @seanhaufler, thanks again for the heads up, version 2.2.11 is now released that adds support for dark mode. Let me know if you have any other issues
