### ISSUE TITLE
iOS 8 compatibility

### ISSUE THREAD

**Issue by jschwendt** [Driftt/drift-sdk-ios#9]
Currently the Podspec lists iOS 9 as the minimum SDK.  Any chance you can roll that back to iOS 8?  We generally support n-2 at this point in the cycle.  I can't see any dependencies that would be negatively affected by this change.

**Comment by eoinoconnell** [comment]
Just looking into this for you now

**Comment by eoinoconnell** [comment]
This is solved in #12
