### ISSUE TITLE
  Can someone help me fix this? I installed the drift-sdk-ios module but it didn't work. show error:

### ISSUE THREAD

**Issue by Phu-Hoang** [Driftt/drift-sdk-ios#94]
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening appxcworkspace

** BUILD FAILED **

The following build commands failed:
        CompileC /Users/user/app/ios/build/app/Build/Intermediates.noindex/RNDrift.build/Debug-iphonesimulator/RNDrift.build/Objects-normal/x86_64/RNDrift.o RNDrift.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
. Run CLI with --verbose flag for more details.

**Comment by eoinoconnell** [comment]
Hello, how are you integrating the drift sdk into your project?

**Comment by Phu-Hoang** [comment]
I used use_frameworks and add pod 'Drift', '~> 2.2.1' at Podfile
