### ISSUE TITLE
Cartfile needs to be updated for Carthage users

### ISSUE THREAD

**Issue by sjoness** [Driftt/drift-sdk-ios#96]
The `Cartfile` is quite out-of-date which means installing this SDK with Carthage causes an error thrown, due to the nested dependencies targeting old versions, not supported in Xcode 11 / Swift 5+.

This `Cartfile` below matches the dependency versions from the `Podfile`

```
github "tristanhimmelman/ObjectMapper" ~> 3.4
github "alamofire/AlamofireImage" ~> 3.3
github "SVProgressHUD/SVProgressHUD" ~> 2.0
github "daltoniam/Starscream" ~> 3.0.0
```

**Comment by eoinoconnell** [comment]
Hi, thanks for the feedback, we currently don't support Carthage actively. We will look into adding it in a future release. The current Cartfile shouldn't be on the repo.
