### ISSUE TITLE
Drift pod 2.3.0 has 9 compile error

### ISSUE THREAD

**Issue by ushernut** [Driftt/drift-sdk-ios#99]
After pod installed, run build, it gives 9 compile error on Drift right away, here is the first one:

/Users/simon/Development/DuPro/dupro_ios/Pods/Drift/Drift/Birdsong/Socket.swift:154:1: Type 'Socket' does not conform to protocol 'WebSocketDelegate'
/Users/simon/Development/DuPro/dupro_ios/Pods/Drift/Drift/Birdsong/Socket.swift:33:23: Value of type 'WebSocket' has no member 'isConnected'

Looks like you have upgraded Starscream from 3.1.0 to 3.1.1 lately, and this brings the error.

**Comment by eoinoconnell** [comment]
Hi, sorry for the delay, yes you are correct, it is actually due to a Starscream moving to 4.0. 

We have the resolved in the master branch but are still testing before we release a version so you could use that for the moment

**Comment by MarcoDaniele** [comment]
I have the same problem. how can I solve this?

**Comment by MarcoDaniele** [comment]
Found the solution myself 👍🏻, just write your Podfile like this: 
`pod 'Drift', '2.3.0'`
`pod 'Starscream', '3.1.1'`

or just use the master branch: 
`pod 'Drift', :git=>'https://github.com/Driftt/drift-sdk-ios.git'`

**Comment by ushernut** [comment]
> `pod 'Drift', '2.3.0'`
> `pod 'Starscream', '3.1.1'`

After compiling and start the conversation, it just keep display loading... does that happen to you as well? @MarcoDaniele

**Comment by eoinoconnell** [comment]
Hi @ushernut , can you confirm you have setup the SDK with an embedId and user before opening the conversation views?

**Comment by eoinoconnell** [comment]
Version 2.3.1 of the pod has been released so you should no longer require the pod file work arounds
